# Generated by Django 3.2.25 on 2024-07-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='')),
                ('contact', models.IntegerField(default='')),
                ('Address', models.CharField(default='', max_length=50)),
                ('Mail', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
