# Generated by Django 3.2.25 on 2024-07-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pframe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='')),
                ('Contect', models.IntegerField(default='')),
                ('Address', models.CharField(default='', max_length=50)),
                ('Mail', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='design',
            old_name='contact',
            new_name='contect',
        ),
    ]
