# Generated by Django 3.2.25 on 2024-07-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pframe', '0002_auto_20240723_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='design',
        ),
    ]
